version: "3.8"

services:
  # PostgreSQL 서비스 - User Service용
  postgres-user:
    image: postgres:15-alpine
    container_name: career-lens-postgres-user
    restart: unless-stopped
    environment:
      POSTGRES_DB: user_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_user_data:/var/lib/postgresql/data
    networks:
      - career-lens-network

  # PostgreSQL 서비스 - Auth Service용
  postgres-auth:
    image: postgres:15-alpine
    container_name: career-lens-postgres-auth
    restart: unless-stopped
    environment:
      POSTGRES_DB: auth_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5433:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    networks:
      - career-lens-network

  # User Service
  user-service:
    build:
      context: ./apps/user-service
      dockerfile: ../../Dockerfile
      target: production
    container_name: career-lens-user-service
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3001
      DB_HOST: postgres-user
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password123
      DB_DATABASE: user_service
    ports:
      - "3001:3001"
    depends_on:
      - postgres-user
    networks:
      - career-lens-network
    volumes:
      - ./logs:/app/logs

  # Auth Service
  auth-service:
    build:
      context: ./apps/auth-service
      dockerfile: ../../Dockerfile
      target: production
    container_name: career-lens-auth-service
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3002
      DB_HOST: postgres-auth
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password123
      DB_DATABASE: auth_service
      JWT_SECRET: your-super-secret-jwt-key-for-production
    ports:
      - "3002:3002"
    depends_on:
      - postgres-auth
    networks:
      - career-lens-network
    volumes:
      - ./logs:/app/logs

  # pgAdmin (옵션 - 개발용)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: career-lens-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@career-lens.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "8080:80"
    depends_on:
      - postgres-user
      - postgres-auth
    networks:
      - career-lens-network
    profiles:
      - dev

# 볼륨 정의
volumes:
  postgres_user_data:
    driver: local
  postgres_auth_data:
    driver: local

# 네트워크 정의
networks:
  career-lens-network:
    driver: bridge
