version: '3.8'

services:
  # PostgreSQL 데이터베이스
  postgres:
    image: postgres:15
    container_name: career-lens-postgres
    environment:
      POSTGRES_DB: career_lens
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - career-lens-network

  # 인증 서비스
  auth-service:
    build:
      context: .
      dockerfile: apps/auth-service/Dockerfile
    container_name: career-lens-auth-service
    environment:
      NODE_ENV: development
      PORT: 3001
      GRPC_URL: 0.0.0.0:50051
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_DATABASE: career_lens
      JWT_SECRET: your-secret-key
    ports:
      - "3001:3001"  # HTTP
      - "50051:50051"  # gRPC
    depends_on:
      - postgres
    networks:
      - career-lens-network
    volumes:
      - ./proto:/app/proto

  # 사용자 서비스
  user-service:
    build:
      context: .
      dockerfile: apps/user-service/Dockerfile
    container_name: career-lens-user-service
    environment:
      NODE_ENV: development
      PORT: 3002
      GRPC_URL: 0.0.0.0:50052
      AUTH_SERVICE_GRPC_URL: auth-service:50051
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_DATABASE: career-lens
      JWT_SECRET: your-secret-key
    ports:
      - "3002:3002"  # HTTP
      - "50052:50052"  # gRPC
    depends_on:
      - postgres
      - auth-service
    networks:
      - career-lens-network
    volumes:
      - ./proto:/app/proto

  # API Gateway (선택사항)
  api-gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
    container_name: career-lens-api-gateway
    environment:
      NODE_ENV: development
      PORT: 3000
      AUTH_SERVICE_URL: http://auth-service:3001
      USER_SERVICE_URL: http://user-service:3002
      AUTH_SERVICE_GRPC_URL: auth-service:50051
      USER_SERVICE_GRPC_URL: user-service:50052
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - user-service
    networks:
      - career-lens-network

volumes:
  postgres_data:

networks:
  career-lens-network:
    driver: bridge
