version: "3.8"

services:
  # 개발용 PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: career-lens-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: career_lens_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - career-lens-dev-network

  # 개발용 NestJS 애플리케이션 (핫 리로드)
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: career-lens-app-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password123
      DB_DATABASE: career_lens_dev
      JWT_SECRET: your-dev-jwt-secret-key
    ports:
      - "3000:3000"
      - "9229:9229" # 디버깅 포트
    depends_on:
      - postgres
    networks:
      - career-lens-dev-network
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs

  # pgAdmin (개발용)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: career-lens-pgadmin-dev
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@career-lens.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - career-lens-dev-network

volumes:
  postgres_dev_data:
    driver: local

networks:
  career-lens-dev-network:
    driver: bridge
