services:
  # PostgreSQL 서비스 - 통합 User Service용
  postgres:
    image: postgres:15-alpine
    container_name: career-lens-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: user_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - career-lens-network

  # 통합 User Service (인증 + 사용자 관리)
  user-service:
    build:
      context: .
      dockerfile: ./apps/user-service/Dockerfile
    container_name: career-lens-user-service
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3001
      GRPC_URL: 0.0.0.0:50051
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password123
      DB_DATABASE: user_service
      JWT_SECRET: your-super-secret-jwt-key-for-development
    ports:
      - "3001:3001" # HTTP
      - "50051:50051" # gRPC
    depends_on:
      - postgres
    networks:
      - career-lens-network
    volumes:
      - ./logs:/app/logs

  # API Gateway
  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
    container_name: career-lens-api-gateway
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3000
      USER_SERVICE_GRPC_URL: user-service:50051
    ports:
      - "3000:3000"
    depends_on:
      - user-service
    networks:
      - career-lens-network
    volumes:
      - ./logs:/app/logs

  # pgAdmin (옵션 - 개발용)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: career-lens-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@career-lens.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - career-lens-network
    profiles:
      - dev

# 볼륨 정의
volumes:
  postgres_data:
    driver: local

# 네트워크 정의
networks:
  career-lens-network:
    driver: bridge
