version: "3.8"

services:
  # PostgreSQL 서비스
  postgres:
    image: postgres:15-alpine
    container_name: career-lens-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: career_lens
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - career-lens-network

  # NestJS 애플리케이션 서비스
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: career-lens-app
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password123
      DB_DATABASE: career_lens
      JWT_SECRET: your-super-secret-jwt-key-for-production
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - career-lens-network
    volumes:
      - ./logs:/app/logs

  # pgAdmin (옵션 - 개발용)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: career-lens-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@career-lens.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - career-lens-network
    profiles:
      - dev

# 볼륨 정의
volumes:
  postgres_data:
    driver: local

# 네트워크 정의
networks:
  career-lens-network:
    driver: bridge
