version: "3.8"

services:
  # 개발용 PostgreSQL - User Service용
  postgres-user:
    image: postgres:15-alpine
    container_name: career-lens-postgres-user-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: user_service_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_user_dev_data:/var/lib/postgresql/data
    networks:
      - career-lens-dev-network

  # 개발용 PostgreSQL - Auth Service용
  postgres-auth:
    image: postgres:15-alpine
    container_name: career-lens-postgres-auth-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: auth_service_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5433:5432"
    volumes:
      - postgres_auth_dev_data:/var/lib/postgresql/data
    networks:
      - career-lens-dev-network

  # 개발용 User Service (핫 리로드)
  user-service:
    build:
      context: ./apps/user-service
      dockerfile: ../../Dockerfile.dev
    container_name: career-lens-user-service-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3001
      DB_HOST: postgres-user
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password123
      DB_DATABASE: user_service_dev
    ports:
      - "3001:3001"
      - "9230:9229" # 디버깅 포트
    depends_on:
      - postgres-user
    networks:
      - career-lens-dev-network
    volumes:
      - ./apps/user-service:/app
      - /app/node_modules
      - ./logs:/app/logs

  # 개발용 Auth Service (핫 리로드)
  auth-service:
    build:
      context: ./apps/auth-service
      dockerfile: ../../Dockerfile.dev
    container_name: career-lens-auth-service-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3002
      DB_HOST: postgres-auth
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password123
      DB_DATABASE: auth_service_dev
      JWT_SECRET: your-dev-jwt-secret-key
    ports:
      - "3002:3002"
      - "9231:9229" # 디버깅 포트
    depends_on:
      - postgres-auth
    networks:
      - career-lens-dev-network
    volumes:
      - ./apps/auth-service:/app
      - /app/node_modules
      - ./logs:/app/logs

  # pgAdmin (개발용)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: career-lens-pgadmin-dev
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@career-lens.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "8080:80"
    depends_on:
      - postgres-user
      - postgres-auth
    networks:
      - career-lens-dev-network

volumes:
  postgres_user_dev_data:
    driver: local
  postgres_auth_dev_data:
    driver: local

networks:
  career-lens-dev-network:
    driver: bridge
